### ISSUE TITLE
[BUG] HOUSE INVENTORY

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#1915]
### Your Discord Name

Roseii

### A clear and concise description of what the bug is

Even when you are underweight you cannot put anything back into house inventory. I'm currently at 10459 out of 11000 and cannot put anything back in. It doesn't matter if it is 1lb .  It gives the error "You cannot carry that much" when trying to put something in the storage. The only one this is happening to me on is the ranch house interior. The big garage and small house with two bedrooms work fine

### Steps to Reproduce the Bug

1. Take something out of storage
2. Choose even 1bb of anything
3. Unable to put item in storage. 

### Expected Behavior

To be able to put items into your storage again when you are underweight. 

### Screenshots/Videos

https://cdn.discordapp.com/attachments/1049113517749456998/1171585657504792657/image.png?ex=655d372b&is=654ac22b&hm=46481ba8d62d38da422da8a3bc97bda56c2fab9f28f1bfc20b6f7d57f7fcf10d&

**Comment by RoseiiNaytool** [comment]
These are the errors in the F8 menu, but I don't think it has anything to do with the storage:
https://cdn.discordapp.com/attachments/1049113517749456998/1171586409925197935/image.png?ex=655d37df&is=654ac2df&hm=62d1ca5ab43f7ec70bef95be875f16ac4d24bee60aa0d1f58006fc4d5571d4b2&

**Comment by turbo-toad** [comment]
They mentioned on my post previously that they decided its the way it is I guess. Best thing to do rn is just find a friend with a pounder custom and transport stuff to the storage units.

**Comment by RoseiiNaytool** [comment]
It wasn't the weight system, I have less than what the inventory holds. It seems to be an issue with just my casino weight for some reason. I can't put anything back into it even with 2k less than what it holds. My other ranch house inventory is working fine.

**Comment by RoseiiNaytool** [comment]
We took some stuff out of the storage and then slowly started adding it back in. Out of the 11k storage it says it has you can fill it up to 8850 before it says there is no more room in the storage. Thought I would help test out issues.

**Comment by xXJamieXx** [comment]
I have a feeling this is just a visual confusion with how individual item weight is being displayed currently. I have corrected the visual inconsistency next restart but please let me know if this is not the case.

**Comment by RoseiiNaytool** [comment]
Than you. I'll take a look at it after this restart.
Peggy Murrey
Lawton, OK. Chapter Leader and Regional Chapter Supervisor

~Would you like a Jelly Baby?~

**Comment by xXJamieXx** [comment]
@RoseiiNaytool update on this?

**Comment by RoseiiNaytool** [comment]
I still can't put over  like 8900 into the 11000 available for storage in
the casino. I've tried everything, including taking everything out and
putting it back in.
